//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expositor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Expositor()
        {
            this.Conferencias = new HashSet<Conferencia>();
        }
    
        public int ID { get; set; }
        public string Nombre { get; set; }
        public int Pais { get; set; }
        public string Titulos { get; set; }
        public string Descripcion { get; set; }
        public string Linked { get; set; }
        public string Facebook { get; set; }
        public string Twitter { get; set; }
        public string PaginaWeb { get; set; }
        public string Celular { get; set; }
    
        public virtual Pai Pai { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Conferencia> Conferencias { get; set; }
    }
}
