//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salone
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Salone()
        {
            this.Conferencias = new HashSet<Conferencia>();
        }
    
        public int ID { get; set; }
        public string Salon { get; set; }
        public int Lugar { get; set; }
        public int CapacidadPersonas { get; set; }
        public int MesasNegocios { get; set; }
        public string Tipo { get; set; }
        public bool Video { get; set; }
        public bool Audio { get; set; }
        public string Otros { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Conferencia> Conferencias { get; set; }
        public virtual Lugar Lugar1 { get; set; }
    }
}
