//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int ID { get; set; }
        public string NombreCompleto { get; set; }
        public string NombreUsuario { get; set; }
        public string Pass { get; set; }
        public string Email { get; set; }
        public Nullable<int> Empresa { get; set; }
        public int Documento { get; set; }
        public string Direccion { get; set; }
        public int Perfil { get; set; }
        public bool Estado { get; set; }
    
        public virtual Empresa Empresa1 { get; set; }
        public virtual Perfile Perfile { get; set; }
    }
}
